spring:
  application:
    name: morning-phrases
  data:
    mongodb:
      uri: ${MONGODB_URL}

gemini:
  api:
    url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"

whatsapp:
  api:
    url: ${WHATSAPP_API_URL}